### ISSUE TITLE
"Unable to satisfy constraints"

### ISSUE THREAD

**Issue by Serkora** [acedened/TheChan.iOS#11]
Задалбывающая ошибка при открытии каждого треда. Проблема в индикаторе стейт контроллера, которому задана фиксированная ширина в 36 единиц, но при прятании ширина должна становиться 0.
Решить можно либо изменением условия на "меньше или равно", либо вовсе удалением, всё нормально работает (сдвигает текст и т.д.).

**Comment by acedened** [comment]
А, надо просто приоритет у ширины поменять, сейчас исправлю.
