### ISSUE TITLE
Various threadViewController-related stuff

### ISSUE THREAD

**Issue by Serkora** [acedened/TheChan.iOS#12]
Несколько проблем:
1. Если при рефреше добавились посты, то часто ломается скролл наверх по тапу статус бара.

2. Если спуститься в самый низ треда*, нажать обновление, не получить новых постов и потом нажать кнопку обновления ещё раз — экран прыгает немного наверх, на 1-2 поста (в зависимости от их размера). Лишь несколько раз не срабатывало.
* Либо кнопкой, либо проскроллить и нажать в верхнюю часть для появления нав бара. В большинстве случаев воспроизводится лишь с одним из вариантов.

3. Давно спросить хотел: а почему количество новых постов считается с момета открытия треда? https://github.com/acedened/TheChan.iOS/blob/master/TheChan/ThreadTableViewController.swift#L217 Тут разве не **=** должно быть?

4. Скролл по нажатию нажатию на название треда работает хреново, однако, с каждым обнолением останавливаясь всё раньше и раньше. Иногда аж 4 раза нужно кликать, чтобы до верха добраться. Наверное, нужно вернуть прежнее решение со скроллом к нулевой ячейке, как на доске (не забыв проверить количество постов).

Идеи:
1. А почему бы не передавать в контроллер треда и его название, а не только борду/номер поста? Всё равно на момент перехода уже известно (как с доски, так и из избранного).

**Comment by acedened** [comment]
3. Там все правильно, увеличивается количество непрочитанных постов.

1. Моэно

**Comment by Serkora** [comment]
Так а прочитанными же они нигде не отмечаются, в итоге эта цифра только монотонно увеличивается. Потом допилишь, получается?

**Comment by acedened** [comment]
Да.
