### ISSUE TITLE
Креш при открытии доски

### ISSUE THREAD

**Issue by Serkora** [acedened/TheChan.iOS#13]
При открытии некоторых досок Kanna не может правильно обработать хтмл ОП-поста, вылетая на 70-ой строке Pods/Kanna/libxmlHTMLNode.swift:
`            if nodePtr != nil {
                return String(cString: UnsafePointer((nodePtr?.pointee.name)!))
            }`
> fatal error: unexpectedly found nil while unwrapping an Optional value

(Не помогла проверка на nil, лол.)

В данный момент замечено по крайней мере на: /diy, /hc, /pr, /fg, при этом последние два точно ломались ещё с самого начала.

**Comment by acedened** [comment]
Канну вообще наверное менять придется, ибо в релизной сборке она падает при заходе на любую доску.

**Comment by Serkora** [comment]
Заменил канну на https://github.com/cezheng/Fuzi

Больше не крешится, работает нормально, процентов на 10 даже быстрее. Единственная проблема — в прикреплённом треде /fg/ (https://2ch.hk/fg/res/434697.html)  #атрибут NSLink почему-то на два символа съехал, хотя во всех других местах всё нормально. В принципе, подобные ОП-посты надо как-то по-особенному обрабатывать в любом случае. Ну или нафиг их, и так норм.

Ещё заменил \r\n и \t (плейн-текстом) на, собственно, таб и новую строку. Преимущесво перед 2ch-browser'ом!

#18
