### ISSUE TITLE
Количество постов в треде на доске

### ISSUE THREAD

**Issue by Serkora** [acedened/TheChan.iOS#14]
Может, стоит выводить количество не "пропущенных" постов, а просто полное количество постов? В клиенте эта цифра не имеет никакого смысла же, там всё пропущено. Добавить в `EntityMapper.map(boardId, threads)` что-то такое 
```
let posts = thread["posts"] as! [[String: AnyObject]]
result.omittedPosts += posts.count
```
Ну и переименовать потом лейблы всякие.

**Comment by acedened** [comment]
А, да, это тоже хотел сделать. Сегодня займусь.
