### ISSUE TITLE
Пропадающие картинки

### ISSUE THREAD

**Issue by acedened** [acedened/TheChan.iOS#4]
Иногда при скроллинге превьюшки картинок могут не показываться. Баг очень непонятный. Из того, что известно:
- У dataSource (PostTableViewCell) вызываются numberOfSections и numberOfItemsInSection, но cellForItemAtIndexPath - нет.

**Comment by Serkora** [comment]
А можно подробнее про это? А то я не вижу ничего. Поле для превьюшек не появляется? При скроллинге — это именно во время движения, как я понимаю? Если остановиться, превьюшки появятся?

**Comment by acedened** [comment]
Нет, если быстро скроллить, то картинки в постах могут не появляться. Не важно, остановится скролл или нет.
<img width="487" alt="2016-11-23 16 08 33" src="https://cloud.githubusercontent.com/assets/7037300/20562915/3581cdae-b197-11e6-991e-3c9669fdb514.png">

**Comment by Serkora** [comment]
По всей видимости, проблем в симуляторе, на телефоне я такого добиться не смог, а на компьютере — с первого же тестируемого треда.
Не думаю, что телефон позволит себе пропускать вызовы нужных методов, не андроид же, где даже вызов аналога applicationWillTerminate или viewDidUnload не гарантируется.

**Comment by Serkora** [comment]
Хм, похоже разок проявилось на телефоне, но после скролла туда-сюда всё появилось. Может просто картинка долго грузилась.
В интернете о похожей проблеме пишут прилично, там с неизвестным размером ячейки связано было. Играясь во вскими констреинтами, фиксированными разерами ячеки и Content Mode'а у меня, вроде как, получилось почти починить (выглядеть только всё как говно стало), но потом я всё проебал.

**Comment by acedened** [comment]
Ладно, раз на телефоне не проявляется, пока закрою.

**Comment by Serkora** [comment]
Не, всё же проявилось один раз, так что лучше оставить открытым. Мне кажется это как-то связано с производительностью, нужно бы найти кого-то с 4s на ios 9, чтобы лагало всё.

**Comment by acedened** [comment]
Исправлено с переписыванием разметки
