### ISSUE TITLE
Медленная загрузка тредов. Очень.

### ISSUE THREAD

**Issue by Serkora** [acedened/TheChan.iOS#7]
Собственно, entitymapper работает _очень_ медленно. Какой-нибудь тред в /pa/ на тысячу постов с лёгкостью может открываться секунд 5, при этом сетевая активность там 200-300мс.

Попробовал не обрабатывать пост пока он не потребуется, то есть в `Facade.loadThread` в объекты Post пихать чистый жсон, а уже `cellForRowAt` запускать `EntityMapper.map(post:)`, есил пост ещё не обработан.
Открывает хорошо и быстро, но скролл первый раз лагучий, если крутить быстро, плюс в самый низ по кнопке плохо прокручивается прямо с открытия, иногда за пару постов останавливается, иногда даже за несколько десятков может.

Попробовал после загрузки всех постов запустить асинхронную обработку — лучше, и если не стараться нарочно обогнать её, скролля на максимальной скорости вниз, то силки смус. Прокрутка вниз, к сожалению, всё равно фигово работает, так как из-за анимации он промежуточные ячейки тоже пытается загрузить и теряет драгоценные 100-200мс. 
Если в `goDownButtonTapped` отключить анимацию и обработать последние 10-15 постов сразу при открытии треда, то всё ок.
Однако, если сразу перейти вниз и начать листать вверх — лаги, как и в предыдущем пункте. Можно сразу в обе стороны по массиву постов пойти, конечно, но хватит уже костыли пихать, надо иначе решать.

В общем, в 2ch-browser'е всё хорошо, хотя посты все формируются сразу же. Надо EntityMapper/Markup переделывать, я бы сказал, уж очень медленный, тратить по ~5-7мс на каждый пост на почти последнем железе это не круто, по-моему.

https://github.com/Serkora/TheChan.iOS/tree/thread_performance Вот тут сделано то, что я описал.

**Comment by acedened** [comment]
Попробую потом многопоточную обработку постов сделать.

**Comment by Serkora** [comment]
Так я же сделал уже. Можно ещё один поток для второго ядра, конечно, добавить, плюс изменять уже имеющийся объект, а не создавать новый, заменяя элемент массива, но это мелочи. Я не понимаю, откуда такая нагрузка, там же текст обработать да и всё.

При синхронной обработке постов, кстати, при открытии треда на 1700 постов (в /wrk/ есть) память до 500 мегабайт прыгает, возвращаясь до 130 в конце. Надо бы заранее создавать массив на нужное количество объектов.
При этом мой асинхронный вариант и в целом памяти гораздо меньше потребляет, что довольно странно.

**Comment by acedened** [comment]
Это асинхронный, а я говорю именно про многопоточность. Т.е. при загрузке треда запускать  несколько потоков для парсинга постов.

**Comment by acedened** [comment]
Хотя может просто парсер медленный или код парсинга - говно.

**Comment by Serkora** [comment]
Ну, больше двух потоков производительность не повысят, в любом случае. Поиграюсь с парсером этим, может, на досуге.

**Comment by Serkora** [comment]
Виновато поле subject и его обработка:
`post.subject = String(htmlEncodedString: raw["subject"] as? String ?? "")`
При исключении среднее время на пост падает с 4.6 до 0.7мс. Довольно заметно, особенно учитывая то, что оно используется лишь в оп-посте.

**Comment by acedened** [comment]
Странно, неужели обращение к несуществующему полю так затратно?

**Comment by acedened** [comment]
А, кажись понял, в чем проблема. Это https://github.com/acedened/TheChan.iOS/blob/master/TheChan/HTMLEntities.swift#L12 медленно работает.

**Comment by acedened** [comment]
Исправлено в 1170607

**Comment by acedened** [comment]
Теперь тред на 1700 постов грузится за секунду.

**Comment by Serkora** [comment]
Память, получается, тоже эта же фигня выжирала, теперь всё нормально.

Вообще, если markup убрать, то среднее с ~0.3мс до 0.03 падает, так что ещё есть, куда стремиться, лол.
